import { 
  CheckCircle2, 
  Leaf, 
  HardHat, 
  Zap, 
  Flame, 
  Plane, 
  Ban, 
  Target, 
  GraduationCap, 
  ClipboardCheck, 
  Siren, 
  Car, 
  Eye, 
  FileText, 
  FlaskConical 
} from "lucide-react";

export const services = [
  {
    title: "ISO 9001:2015",
    slug: "iso-9001-2015",
    description: "Quality Management Systems focused on meeting customer requirements and enhancing satisfaction.",
    label: "QMS Certification",
    icon: CheckCircle2,
    category: "ISO Certification",
  },
  {
    title: "ISO 14001:2015",
    slug: "iso-14001-2015",
    description: "Environmental Management systems designed to reduce environmental footprint and improve sustainability.",
    label: "EMS Certification",
    icon: Leaf,
    category: "ISO Certification",
  },
  {
    title: "ISO 45001:2018",
    slug: "iso-45001-2018",
    description: "Occupational Health and Safety standards to ensure employee welfare and workplace safety compliance.",
    label: "OH+SMS Certification",
    icon: HardHat,
    category: "ISO Certification",
  },
  {
    title: "ISO 50001:2018",
    slug: "iso-50001-2018",
    description: "Energy Management Systems (EnMS) to help organizations improve energy performance and efficiency.",
    label: "EnMS Certification",
    icon: Zap,
    category: "ISO Certification",
  },
  {
    title: "ISO 3834:2021",
    slug: "iso-3834-2021",
    description: "Quality requirements for fusion welding of metallic materials, ensuring technical excellence.",
    label: "Welding Quality",
    icon: Flame,
    category: "ISO Certification",
  },
  {
    title: "AS9120B Aerospace",
    slug: "as9120b-aerospace",
    description: "Quality Management System requirements for Aviation, Space, and Defense Distributors.",
    label: "Aerospace Standard",
    icon: Plane,
    category: "ISO Certification",
  },
  {
    title: "RoHS Certification",
    slug: "rohs-certification",
    description: "Restriction of Hazardous Substances compliance for electronic and electrical equipment.",
    label: "Hazardous Compliance",
    icon: Ban,
    category: "ISO Certification",
  },
  {
    title: "ZED Certification",
    slug: "zed-certification",
    description: "Zero Defect Zero Effect (ZED) Bronze and Silver certification services for sustainable manufacturing.",
    label: "ZED Bronze/Silver",
    icon: Target,
    category: "ISO Certification",
  },
  {
    title: "Technical Training",
    slug: "technical-training",
    description: "Comprehensive training in 5'S, 4M, Kaizen, Poka-Yoke, and 7 QC Tools for system improvement.",
    label: "System Improvement",
    icon: GraduationCap,
    category: "Technical Training",
  },
  {
    title: "WPQR & TTR",
    slug: "wpqr-ttr",
    description: "Welding Procedure Qualification Record and Technical Training Report certification services.",
    label: "Technical Records",
    icon: ClipboardCheck,
    category: "Technical Training",
  },
  {
    title: "Mock-Drill Operations",
    slug: "mock-drill-operations",
    description: "Safety and emergency situation drills to ensure organizational preparedness and response.",
    label: "Safety Readiness",
    icon: Siren,
    category: "Safety & Operations",
  },
  {
    title: "MACE Implementation",
    slug: "mace-implementation",
    description: "Maruti Center for Excellence (MACE) system implementation works for automotive standards.",
    label: "Excellence Works",
    icon: Car,
    category: "Safety & Operations",
  },
  {
    title: "Visual Management",
    slug: "visual-management",
    description: "Making name plates, shine boards, posters, and banners for factory premises display.",
    label: "Branding & Signage",
    icon: Eye,
    category: "Safety & Operations",
  },
  {
    title: "Documentation",
    slug: "documentation",
    description: "Making books, identification tags, and slogans as per process needs for better tracking.",
    label: "Process Tracking",
    icon: FileText,
    category: "Safety & Operations",
  },
  {
    title: "Material Testing",
    slug: "material-testing",
    description: "Facilitating material testing services by verified third-party laboratories for quality assurance.",
    label: "Quality Testing",
    icon: FlaskConical,
    category: "Safety & Operations",
  },
];
